# Generated by Django 3.2.8 on 2021-11-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_info', models.TextField()),
                ('places_to_visit', models.TextField()),
                ('recommened_hotel', models.TextField()),
            ],
        ),
    ]
