# Generated by Django 3.2.8 on 2021-12-13 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('create_itinerary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ('-published_date',)},
        ),
        migrations.AddField(
            model_name='itinerary',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
