# Generated by Django 2.0.3 on 2022-05-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_itinerary', '0002_auto_20211213_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={},
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='published_date',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='recommened_activities',
            field=models.TextField(default='0000000'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='return_info',
            field=models.TextField(default='0000000'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
