# Generated by Django 2.0.3 on 2022-05-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_itinerary', '0003_auto_20220508_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='recommened_activities',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='return_info',
            field=models.TextField(default=''),
        ),
    ]
